'use client'

import { useState, useEffect, useRef } from 'react'

const RED   = '#cc1a2e'
const BRAND = '#1d3a5c'

interface ReportData {
  sprint: { name: string; startDate: string; endDate: string } | null
  user: string
  stats: { done: number; open: number; pct: number; totalMins: number; sessionCount: number; pendingCount: number }
  accomplished: { id: number; subject: string; project: string }[]
  inProgress: { id: number; subject: string; project: string }[]
  backlog: { id: number; subject: string }[]
  timeByTask: { id: number; subject: string; mins: number; fmt: string }[]
  byDate: { date: string; count: number; mins: number; fmt: string }[]
  incoming: number
  hasAI: boolean
}

type Format = 'standup' | 'sprint-review' | 'weekly'

function fmtMins(m: number) {
  if (m < 60) return `${m}m`
  const h = Math.floor(m / 60), min = m % 60
  return min > 0 ? `${h}h ${min}m` : `${h}h`
}

function buildTemplate(data: ReportData, format: Format): string {
  const sprintName = data.sprint?.name ?? 'Current Sprint'
  const today = new Date().toLocaleDateString('en-US', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })

  if (format === 'standup') {
    const done = data.accomplished.slice(0, 5).map(t => `  - [#${t.id}] ${t.subject}`).join('\n') || '  - (none yet)'
    const today2 = data.inProgress.slice(0, 3).map(t => `  - [#${t.id}] ${t.subject}`).join('\n') || '  - (continuing sprint tasks)'
    const blocker = data.stats.pendingCount > 0 ? `  - ${data.stats.pendingCount} sessions pending push to OP` : '  - None'
    return `**Daily Standup — ${today}**\n\n**Yesterday:**\n${done}\n\n**Today:**\n${today2}\n\n**Blockers:**\n${blocker}`
  }

  if (format === 'sprint-review') {
    const accomplished = data.accomplished.map(t => `- [#${t.id}] ${t.subject}${t.project ? ` *(${t.project})*` : ''}`).join('\n') || '- None completed yet'
    const inProgress = data.inProgress.slice(0, 5).map(t => `- [#${t.id}] ${t.subject}${t.project ? ` *(${t.project})*` : ''}`).join('\n') || '- None'
    const topTime = data.timeByTask.slice(0, 5).map(t => `| #${t.id} | ${t.subject} | ${t.fmt} |`).join('\n')
    return `# Sprint Review — ${sprintName}

**Date:** ${today}
**Team Member:** ${data.user}

---

## Summary

| Metric | Value |
|--------|-------|
| Tasks Completed | ${data.stats.done} / ${data.stats.done + data.stats.open} (${data.stats.pct}%) |
| Total Time Logged | ${fmtMins(data.stats.totalMins)} |
| Sessions Recorded | ${data.stats.sessionCount} |
| Tasks In Progress | ${data.stats.open} |

---

## Accomplished ✅

${accomplished}

---

## In Progress 🔄

${inProgress}

---

## Time Breakdown

| Task | Time |
|------|------|
${topTime || '| — | — |'}

---

*Generated by ISL · ${new Date().toISOString().slice(0, 10)}*`
  }

  // weekly
  const accomplished = data.accomplished.slice(0, 8).map(t => `- [#${t.id}] ${t.subject}`).join('\n') || '- None completed this week'
  const ongoing = data.inProgress.slice(0, 4).map(t => `- [#${t.id}] ${t.subject}`).join('\n') || '- None'
  return `# Weekly Work Summary

**Week ending:** ${today}
**Name:** ${data.user}
**Sprint:** ${sprintName}

---

## Highlights

- Completed **${data.stats.done} tasks** (${data.stats.pct}% of sprint)
- Logged **${fmtMins(data.stats.totalMins)}** across ${data.stats.sessionCount} sessions
${data.stats.pendingCount > 0 ? `- **${data.stats.pendingCount} sessions** still pending push to OP\n` : ''}
---

## Tasks Completed

${accomplished}

---

## Ongoing Work

${ongoing}

---

## Time Investment

Total: **${fmtMins(data.stats.totalMins)}** across ${data.stats.sessionCount} sessions
${data.timeByTask.slice(0, 3).map(t => `- ${t.subject}: ${t.fmt}`).join('\n')}

---

*Generated by ISL · ${new Date().toISOString().slice(0, 10)}*`
}

interface Props { onClose: () => void }

export default function SprintReportModal({ onClose }: Props) {
  const [data, setData]       = useState<ReportData | null>(null)
  const [loading, setLoading] = useState(true)
  const [format, setFormat]   = useState<Format>('sprint-review')
  const [output, setOutput]   = useState('')
  const [generating, setGenerating] = useState(false)
  const [useAI, setUseAI]     = useState(false)
  const [copied, setCopied]   = useState(false)
  const abortRef = useRef<AbortController | null>(null)

  useEffect(() => {
    fetch('/api/sprint/report').then(r => r.json()).then(d => {
      setData(d)
      setUseAI(d.hasAI)
      setOutput(buildTemplate(d, 'sprint-review'))
    }).catch(() => {}).finally(() => setLoading(false))
  }, [])

  // Regenerate template when format changes (only if not AI-generated)
  useEffect(() => {
    if (data && !generating) setOutput(buildTemplate(data, format))
  }, [format]) // eslint-disable-line react-hooks/exhaustive-deps

  async function generateAI() {
    if (!data) return
    setGenerating(true)
    setOutput('')
    abortRef.current = new AbortController()
    try {
      const res = await fetch('/api/sprint/report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ reportData: data, format }),
        signal: abortRef.current.signal,
      })
      if (!res.ok) {
        const err = await res.json().catch(() => ({ error: `HTTP ${res.status}` }))
        setOutput(`⚠️ ${err.error ?? 'Failed to generate'}`)
        return
      }
      const reader = res.body!.getReader()
      const dec = new TextDecoder()
      let full = ''
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        full += dec.decode(value, { stream: true })
        setOutput(full)
      }
    } catch (e: unknown) {
      if ((e as Error).name !== 'AbortError') setOutput('⚠️ Connection error')
    } finally {
      setGenerating(false)
      abortRef.current = null
    }
  }

  function copy() {
    navigator.clipboard.writeText(output)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const FORMATS: { id: Format; label: string; desc: string }[] = [
    { id: 'sprint-review', label: 'Sprint Review',  desc: 'Full sprint summary with metrics & task list' },
    { id: 'weekly',        label: 'Weekly Report',  desc: 'Manager-ready weekly work summary' },
    { id: 'standup',       label: 'Daily Standup',  desc: 'Yesterday / Today / Blockers format' },
  ]

  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4" onClick={e => { if (e.target === e.currentTarget) onClose() }}>
      <div className="bg-white dark:bg-gray-900 rounded-2xl shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 dark:border-gray-800 flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center text-white font-bold text-sm"
              style={{ background: `linear-gradient(135deg, ${BRAND}, #2a5298)` }}>
              📋
            </div>
            <div>
              <h2 className="text-sm font-black text-gray-900 dark:text-gray-100">Sprint Report Generator</h2>
              {data?.sprint && (
                <p className="text-[10px] text-gray-400">{data.sprint.name} · {data.sprint.startDate} → {data.sprint.endDate}</p>
              )}
            </div>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 text-lg w-8 h-8 flex items-center justify-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition">✕</button>
        </div>

        {loading ? (
          <div className="flex items-center justify-center h-48">
            <div className="w-6 h-6 rounded-full border-2 border-t-transparent animate-spin" style={{ borderColor: `${RED} ${RED} ${RED} transparent` }} />
          </div>
        ) : (
          <div className="flex flex-1 min-h-0">

            {/* Left panel — controls */}
            <div className="w-64 flex-shrink-0 border-r border-gray-100 dark:border-gray-800 p-5 flex flex-col gap-5 overflow-y-auto">

              {/* Sprint stats */}
              {data && (
                <div className="space-y-2">
                  <p className="text-[9px] font-black uppercase tracking-widest text-gray-400">Sprint Stats</p>
                  <div className="rounded-xl border border-gray-100 dark:border-gray-700 p-3 space-y-2">
                    <div className="flex justify-between text-xs">
                      <span className="text-gray-500">Completed</span>
                      <span className="font-bold text-green-600">{data.stats.done} tasks</span>
                    </div>
                    <div className="flex justify-between text-xs">
                      <span className="text-gray-500">In Progress</span>
                      <span className="font-bold text-blue-600">{data.stats.open} tasks</span>
                    </div>
                    <div className="flex justify-between text-xs">
                      <span className="text-gray-500">Time Logged</span>
                      <span className="font-bold" style={{ color: BRAND }}>{fmtMins(data.stats.totalMins)}</span>
                    </div>
                    <div className="w-full h-1.5 bg-gray-100 dark:bg-gray-700 rounded-full overflow-hidden">
                      <div className="h-full rounded-full" style={{ width: `${data.stats.pct}%`, background: `linear-gradient(to right, ${BRAND}, #2a5298)` }} />
                    </div>
                    <p className="text-center text-[10px] font-bold" style={{ color: BRAND }}>{data.stats.pct}% complete</p>
                  </div>
                </div>
              )}

              {/* Format selector */}
              <div className="space-y-2">
                <p className="text-[9px] font-black uppercase tracking-widest text-gray-400">Report Format</p>
                {FORMATS.map(f => (
                  <button key={f.id} onClick={() => setFormat(f.id)}
                    className={`w-full text-left p-2.5 rounded-xl border text-xs transition ${format === f.id ? 'border-current font-bold' : 'border-gray-100 dark:border-gray-700 text-gray-500 hover:border-gray-300'}`}
                    style={format === f.id ? { borderColor: BRAND, color: BRAND, background: BRAND + '0a' } : {}}>
                    <p className="font-semibold">{f.label}</p>
                    <p className="text-[10px] opacity-60 mt-0.5">{f.desc}</p>
                  </button>
                ))}
              </div>

              {/* Generate buttons */}
              <div className="space-y-2">
                <p className="text-[9px] font-black uppercase tracking-widest text-gray-400">Generate</p>
                {data?.hasAI && (
                  <button onClick={generateAI} disabled={generating}
                    className="w-full py-2.5 rounded-xl text-xs font-bold text-white transition hover:opacity-90 disabled:opacity-50 flex items-center justify-center gap-2"
                    style={{ background: `linear-gradient(135deg, ${BRAND}, #2a5298)` }}>
                    {generating ? (
                      <>
                        <div className="w-3 h-3 rounded-full border border-t-transparent border-white animate-spin" />
                        Generating…
                      </>
                    ) : '✦ AI Generate'}
                  </button>
                )}
                <button onClick={() => { if (data) setOutput(buildTemplate(data, format)) }}
                  disabled={generating}
                  className="w-full py-2.5 rounded-xl text-xs font-bold border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 transition disabled:opacity-50">
                  📄 Use Template
                </button>
                {generating && (
                  <button onClick={() => { abortRef.current?.abort(); setGenerating(false) }}
                    className="w-full py-2 rounded-xl text-xs font-bold text-red-500 border border-red-200 dark:border-red-800 hover:bg-red-50 dark:hover:bg-red-950/30 transition">
                    ■ Stop
                  </button>
                )}
              </div>
            </div>

            {/* Right panel — output */}
            <div className="flex-1 min-w-0 flex flex-col">
              <div className="flex items-center justify-between px-5 py-3 border-b border-gray-100 dark:border-gray-800 flex-shrink-0">
                <p className="text-xs font-semibold text-gray-500">
                  {useAI ? 'AI-generated' : 'Template'} · {FORMATS.find(f => f.id === format)?.label}
                </p>
                <button onClick={copy}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition"
                  style={copied ? { background: '#d1fae5', color: '#065f46' } : { background: BRAND + '12', color: BRAND }}>
                  {copied ? '✓ Copied!' : '⎘ Copy'}
                </button>
              </div>

              <textarea
                value={output}
                onChange={e => setOutput(e.target.value)}
                className="flex-1 w-full resize-none p-5 text-xs font-mono text-gray-700 dark:text-gray-300 bg-gray-50 dark:bg-gray-800/50 focus:outline-none leading-relaxed"
                placeholder="Click 'AI Generate' or 'Use Template' to generate your report…"
                spellCheck={false}
              />
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
